### ISSUE TITLE
DockerEOS

### ISSUE THREAD

**Issue by liderako** [BlockchainLabEOS/EOS-DVO#4]
Тут не доконца понятно.
https://github.com/EOSIO/eos/tree/master/Docker
Build eos image отработало вроде все правильно.
А вот где находиться эти папки я на нашел.
```
sudo rm -rf /data/store/eos # options 
sudo mkdir -p /data/store/eos
```
А эта команда выдает ошибку.
```
docker-compose -f Docker/docker-compose.yml up
```
```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**Comment by BlockchainLabEOS** [comment]
Попробуй так:
sudo docker-compose -f Docker/docker-compose.yml up
должно заработать.

Вот информация к размышлению на эту тему:

This is not a compose issue. If you can't connect to the docker daemon from compose there are a few likely causes:

1. - you forgot to export the DOCKER_ env variables, which is often done by running eval $(docker-machine env default)
2. - there is a network problem between you and the remote docker host (if you're running on a cloud provider)
3. - there is a problem with the docker daemon running in the Virtualbox VM
4. - your user doesn't have access to the docker daemon socket because of permissions (if you're running on a linux host). The solution is to sudo or fix the permissions.
5. - 

These aren't problems that can be solved by compose.

**Comment by liderako** [comment]
С правами sudo заработало.
